name: test

on: push

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Verify gas snapshot is up-to-date
        run: |
          mv .gas-snapshot .gas-snapshot.old
          forge snapshot
          diff .gas-snapshot.old .gas-snapshot
          if [ $? -ne 0 ]; then
              echo "Updated snapshot not committed";
              exit 1;
          fi
